  o Fix call to python-gnupg's verify_file() method (#6022).
